env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - standard-with-typescript
  - plugin:react/recommended
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false
plugins:
  - react
  - jest
rules:
  react/react-in-jsx-scope: [off]
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/no-unsafe-argument': off
  react/prop-types:
    - error
    - ignore:
        - navigation
  '@typescript-eslint/explicit-function-return-type': off
settings:
  react:
    version: 'detect'
