services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
  web:
    build:
      context: ./web
    ports:
      - '5173:5173'
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=development
