services:
  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - DATABASE_URL ${OVERRIDE_DATABASE_URL:-${DATABASE_URL}}
    volumes:
      - ./backend:/app
      - /app/node_modules
  web:
    build:
      context: ./web
    ports:
      - '5173:5173'
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=development
  db:
    build:
      context: ./backend/db
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    ports:
      - '5432:5432'
