env:
  jest: true
parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:jest/recommended'
plugins:
  - '@typescript-eslint'
  - 'jest'
rules:
  jest/no-export: off
  '@typescript-eslint/no-explicit-any': off
