FROM node:lts-slim AS build

WORKDIR /app

COPY package*.json yarn.lock ./
RUN yarn install

COPY . ./
RUN yarn pg
RUN yarn build

ENV PORT=$port
EXPOSE $port

RUN apt-get update -y && apt-get install -y openssl build-essential libpq-dev

CMD yarn pg && yarn start-js-prod
