# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  web-test:
    name: Web Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd web
          yarn install
      - name: Run tests
        run: yarn run test-web

  mobile-test:
    name: Mobile Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: |
          cd mobile
          yarn install
      - name: Run tests
        run: yarn run test-mobile

  code-coverage-web:
    name: Web Code Coverage Report
    uses: irongut/CodeCoverageSummary@v1.3.0
    with:
      filename: web/coverage/cobertura-coverage.xml
      badge: true
      fail_below_min: true
      format: markdown
      hide_branch_rate: false
      hide_complexity: true
      indicators: true
      output: both
      thresholds: '60 80'

  code-coverage-mobile:
    name: Mobile Code Coverage Report
    uses: irongut/CodeCoverageSummary@v1.3.0
    with:
      filename: mobile/coverage/cobertura-coverage.xml
      badge: true
      fail_below_min: true
      format: markdown
      hide_branch_rate: false
      hide_complexity: true
      indicators: true
      output: both
      thresholds: '60 80'

  add-PR-comment:
    name: Add Coverage PR Comment
    uses: marocchino/sticky-pull-request-comment@v2
    if: github.event_name == 'pull_request'
    with:
      recreate: true
      path: code-coverage-results.md
